# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/SmartComm/iVisionmax/screens/user/Diagnostic Module/UI/widgetUI.screen'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widgetUI(object):
    def setupUi(self, widgetUI):
        widgetUI.setObjectName("widgetUI")
        widgetUI.resize(1276, 818)
        self.tabwidget = LTTabWidget(widgetUI)
        self.tabwidget.setGeometry(QtCore.QRect(4, 3, 1270, 810))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.tabwidget.setFont(font)
        self.tabwidget.setAutoFillBackground(False)
        self.tabwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabwidget.setObjectName("tabwidget")
        self.tab_1 = LTWidget()
        self.tab_1.setBackgroundColor(QtGui.QColor(240, 240, 240))
        self.tab_1.setObjectName("tab_1")
        self.tablewidget_Trip_2 = LTTableWidget(self.tab_1)
        self.tablewidget_Trip_2.setGeometry(QtCore.QRect(690, 70, 561, 300))
        self.tablewidget_Trip_2.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"alternate-background-color: rgb(222, 222, 222);")
        self.tablewidget_Trip_2.setObjectName("tablewidget_Trip_2")
        self.tablewidget_Trip_2.setColumnCount(2)
        self.tablewidget_Trip_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_Trip_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_Trip_2.setHorizontalHeaderItem(1, item)
        self.label = LTLabel(self.tab_1)
        self.label.setGeometry(QtCore.QRect(890, 20, 130, 30))
        self.label.setObjectName("label")
        self.trendstatic = TrendStatic(self.tab_1)
        self.trendstatic.setGeometry(QtCore.QRect(20, 390, 1230, 370))
        self.trendstatic.setProperty("tagNameList", ['Obj1.Server_Infra.ram', 'Obj1.Server_Infra.cpu', 'Obj1.Server_Infra.storage'])
        self.trendstatic.setObjectName("trendstatic")
        self.cpu_label_1 = LTLabel(self.tab_1)
        self.cpu_label_1.setGeometry(QtCore.QRect(87, 290, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        self.cpu_label_1.setFont(font)
        self.cpu_label_1.setAutoFillBackground(False)
        self.cpu_label_1.setBackgroundColor(QtGui.QColor(255, 255, 255))
        self.cpu_label_1.setObjectName("cpu_label_1")
        self.cpu_label_3 = LTLabel(self.tab_1)
        self.cpu_label_3.setGeometry(QtCore.QRect(530, 290, 70, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        self.cpu_label_3.setFont(font)
        self.cpu_label_3.setAutoFillBackground(False)
        self.cpu_label_3.setBackgroundColor(QtGui.QColor(255, 255, 255))
        self.cpu_label_3.setObjectName("cpu_label_3")
        self.cpu_label_2 = LTLabel(self.tab_1)
        self.cpu_label_2.setGeometry(QtCore.QRect(298, 290, 90, 40))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        self.cpu_label_2.setFont(font)
        self.cpu_label_2.setAutoFillBackground(False)
        self.cpu_label_2.setBackgroundColor(QtGui.QColor(255, 255, 255))
        self.cpu_label_2.setObjectName("cpu_label_2")
        self.label_29 = LTLabel(self.tab_1)
        self.label_29.setGeometry(QtCore.QRect(685, 65, 570, 310))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("border-color: #f25c5c;\n"
"border-width :1px;\n"
"border-style:solid;\n"
"border-radius:8px;\n"
"    background-color: rgb(255, 255, 255);\n"
"")
        self.label_29.setShadowEnabled(True)
        self.label_29.setShadowRadius(5)
        self.label_29.setShadowOffset(QtCore.QPointF(2.0, 2.0))
        self.label_29.setShadowColor(QtGui.QColor(242, 92, 92, 180))
        self.label_29.setObjectName("label_29")
        self.layoutWidget = QtWidgets.QWidget(self.tab_1)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 70, 631, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ctwgpiechartdonut_4 = ctwgPieChartDonut(self.layoutWidget)
        self.ctwgpiechartdonut_4.setProperty("tagName", "Obj1.Server_Infra.cpu")
        self.ctwgpiechartdonut_4.setProperty("value", 0.0)
        self.ctwgpiechartdonut_4.setObjectName("ctwgpiechartdonut_4")
        self.horizontalLayout_2.addWidget(self.ctwgpiechartdonut_4)
        self.ctwgpiechartdonut_5 = ctwgPieChartDonut(self.layoutWidget)
        self.ctwgpiechartdonut_5.setProperty("tagName", "Obj1.Server_Infra.ram")
        self.ctwgpiechartdonut_5.setProperty("value", 0.0)
        self.ctwgpiechartdonut_5.setObjectName("ctwgpiechartdonut_5")
        self.horizontalLayout_2.addWidget(self.ctwgpiechartdonut_5)
        self.ctwgpiechartdonut_6 = ctwgPieChartDonut(self.layoutWidget)
        self.ctwgpiechartdonut_6.setProperty("tagName", "Obj1.Server_Infra.storage")
        self.ctwgpiechartdonut_6.setProperty("value", 0.0)
        self.ctwgpiechartdonut_6.setObjectName("ctwgpiechartdonut_6")
        self.horizontalLayout_2.addWidget(self.ctwgpiechartdonut_6)
        self.Refresh_mod_active = LTPushButton(self.tab_1)
        self.Refresh_mod_active.setGeometry(QtCore.QRect(1060, 20, 181, 31))
        self.Refresh_mod_active.setObjectName("Refresh_mod_active")
        self.label.raise_()
        self.trendstatic.raise_()
        self.cpu_label_1.raise_()
        self.cpu_label_3.raise_()
        self.cpu_label_2.raise_()
        self.label_29.raise_()
        self.tablewidget_Trip_2.raise_()
        self.layoutWidget.raise_()
        self.Refresh_mod_active.raise_()
        self.tabwidget.addTab(self.tab_1, "Dashboard")
        self.tab_2 = LTWidget()
        self.tab_2.setBackgroundColor(QtGui.QColor(240, 240, 240))
        self.tab_2.setObjectName("tab_2")
        self.tablewidget_Maintenance_4 = LTTableWidget(self.tab_2)
        self.tablewidget_Maintenance_4.setGeometry(QtCore.QRect(260, 100, 780, 420))
        self.tablewidget_Maintenance_4.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"alternate-background-color: rgb(222, 222, 222);")
        self.tablewidget_Maintenance_4.setObjectName("tablewidget_Maintenance_4")
        self.tablewidget_Maintenance_4.setColumnCount(6)
        self.tablewidget_Maintenance_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_Maintenance_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_Maintenance_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_Maintenance_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_Maintenance_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_Maintenance_4.setHorizontalHeaderItem(5, item)
        self.label_10 = LTLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(250, 90, 800, 440))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border-color: #f25c5c;\n"
"border-width :1px;\n"
"border-style:solid;\n"
"border-radius:8px;\n"
"    background-color: rgb(255, 255, 255);\n"
"")
        self.label_10.setShadowEnabled(True)
        self.label_10.setShadowRadius(5)
        self.label_10.setShadowOffset(QtCore.QPointF(2.0, 2.0))
        self.label_10.setShadowColor(QtGui.QColor(242, 92, 92, 180))
        self.label_10.setObjectName("label_10")
        self.label_9 = LTLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(530, 30, 241, 30))
        self.label_9.setObjectName("label_9")
        self.Refresh_appinfo = LTPushButton(self.tab_2)
        self.Refresh_appinfo.setGeometry(QtCore.QRect(861, 30, 181, 31))
        self.Refresh_appinfo.setObjectName("Refresh_appinfo")
        self.label_10.raise_()
        self.tablewidget_Maintenance_4.raise_()
        self.label_9.raise_()
        self.Refresh_appinfo.raise_()
        self.tabwidget.addTab(self.tab_2, "Application Info")
        self.tab_3 = LTWidget()
        self.tab_3.setBackgroundColor(QtGui.QColor(240, 240, 240))
        self.tab_3.setObjectName("tab_3")
        self.tablewidget_Maintenance_2 = LTTableWidget(self.tab_3)
        self.tablewidget_Maintenance_2.setGeometry(QtCore.QRect(260, 100, 790, 410))
        self.tablewidget_Maintenance_2.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"alternate-background-color: rgb(222, 222, 222);")
        self.tablewidget_Maintenance_2.setObjectName("tablewidget_Maintenance_2")
        self.tablewidget_Maintenance_2.setColumnCount(2)
        self.tablewidget_Maintenance_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_2.setHorizontalHeaderItem(1, item)
        self.label_11 = LTLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(251, 90, 810, 430))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("border-color: #f25c5c;\n"
"border-width :1px;\n"
"border-style:solid;\n"
"border-radius:8px;\n"
"    background-color: rgb(255, 255, 255);\n"
"")
        self.label_11.setShadowEnabled(True)
        self.label_11.setShadowRadius(5)
        self.label_11.setShadowOffset(QtCore.QPointF(2.0, 2.0))
        self.label_11.setShadowColor(QtGui.QColor(242, 92, 92, 180))
        self.label_11.setObjectName("label_11")
        self.label_8 = LTLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(530, 30, 241, 30))
        self.label_8.setObjectName("label_8")
        self.Refresh_startlive = LTPushButton(self.tab_3)
        self.Refresh_startlive.setGeometry(QtCore.QRect(870, 30, 181, 31))
        self.Refresh_startlive.setObjectName("Refresh_startlive")
        self.label_11.raise_()
        self.tablewidget_Maintenance_2.raise_()
        self.label_8.raise_()
        self.Refresh_startlive.raise_()
        self.tabwidget.addTab(self.tab_3, "Addition Module Information")
        self.tab = LTWidget()
        self.tab.setObjectName("tab")
        self.tablewidget_Maintenance_10 = LTTableWidget(self.tab)
        self.tablewidget_Maintenance_10.setGeometry(QtCore.QRect(370, 300, 600, 450))
        self.tablewidget_Maintenance_10.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"alternate-background-color: rgb(222, 222, 222);")
        self.tablewidget_Maintenance_10.setObjectName("tablewidget_Maintenance_10")
        self.tablewidget_Maintenance_10.setColumnCount(2)
        self.tablewidget_Maintenance_10.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_Maintenance_10.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_Maintenance_10.setHorizontalHeaderItem(1, item)
        self.label_19 = LTLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(70, 66, 130, 30))
        self.label_19.setObjectName("label_19")
        self.label_22 = LTLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(4, 31, 1250, 250))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("border-color: #f25c5c;\n"
"border-width :1px;\n"
"border-style:solid;\n"
"border-radius:8px;\n"
"    background-color: rgb(255, 255, 255);\n"
"")
        self.label_22.setShadowEnabled(True)
        self.label_22.setShadowRadius(5)
        self.label_22.setShadowOffset(QtCore.QPointF(2.0, 2.0))
        self.label_22.setShadowColor(QtGui.QColor(242, 92, 92, 180))
        self.label_22.setObjectName("label_22")
        self.label_23 = LTLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(365, 295, 610, 460))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("border-color: #f25c5c;\n"
"border-width :1px;\n"
"border-style:solid;\n"
"border-radius:8px;\n"
"    background-color: rgb(255, 255, 255);\n"
"")
        self.label_23.setShadowEnabled(True)
        self.label_23.setShadowRadius(5)
        self.label_23.setShadowOffset(QtCore.QPointF(2.0, 2.0))
        self.label_23.setShadowColor(QtGui.QColor(242, 92, 92, 180))
        self.label_23.setObjectName("label_23")
        self.Refresh_network_stat = LTPushButton(self.tab)
        self.Refresh_network_stat.setGeometry(QtCore.QRect(960, 70, 181, 20))
        self.Refresh_network_stat.setObjectName("Refresh_network_stat")
        self.label_2 = LTLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(13, 40, 1230, 230))
        self.label_2.setBackgroundColor(QtGui.QColor(248, 248, 248))
        self.label_2.setObjectName("label_2")
        self.label_84 = LTLabel(self.tab)
        self.label_84.setGeometry(QtCore.QRect(20, 156, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.label_84.setFont(font)
        self.label_84.setStyleSheet("border-color: #77afe3;\n"
"border-width :1px;\n"
"border-style:solid;\n"
"border-radius:8px;\n"
"    background-color: rgb(255, 255, 255);\n"
"")
        self.label_84.setShadowEnabled(True)
        self.label_84.setShadowRadius(5)
        self.label_84.setShadowOffset(QtCore.QPointF(2.0, 2.0))
        self.label_84.setShadowColor(QtGui.QColor(119, 175, 227))
        self.label_84.setObjectName("label_84")
        self.label_86 = LTLabel(self.tab)
        self.label_86.setGeometry(QtCore.QRect(850, 150, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.label_86.setFont(font)
        self.label_86.setStyleSheet("border-color: #77afe3;\n"
"border-width :1px;\n"
"border-style:solid;\n"
"border-radius:8px;\n"
"    background-color: rgb(255, 255, 255);\n"
"")
        self.label_86.setShadowEnabled(True)
        self.label_86.setShadowRadius(5)
        self.label_86.setShadowOffset(QtCore.QPointF(2.0, 2.0))
        self.label_86.setShadowColor(QtGui.QColor(119, 175, 227))
        self.label_86.setObjectName("label_86")
        self.tagproperties1_38 = tagProperties1(self.tab)
        self.tagproperties1_38.setGeometry(QtCore.QRect(180, 130, 111, 91))
        self.tagproperties1_38.setProperty("tagName", "Obj1.Network_Info.upload_speed_mbps")
        self.tagproperties1_38.setObjectName("tagproperties1_38")
        self.label_14 = LTLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(870, 174, 80, 30))
        self.label_14.setObjectName("label_14")
        self.label_13 = LTLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(470, 174, 120, 30))
        self.label_13.setObjectName("label_13")
        self.tagproperties1_39 = tagProperties1(self.tab)
        self.tagproperties1_39.setGeometry(QtCore.QRect(600, 130, 121, 91))
        self.tagproperties1_39.setProperty("tagName", " ")
        self.tagproperties1_39.setObjectName("tagproperties1_39")
        self.tagproperties1_40 = tagProperties1(self.tab)
        self.tagproperties1_40.setGeometry(QtCore.QRect(990, 130, 131, 91))
        self.tagproperties1_40.setProperty("tagName", "Obj1.Network_Info.total_speed_mbps")
        self.tagproperties1_40.setObjectName("tagproperties1_40")
        self.label_85 = LTLabel(self.tab)
        self.label_85.setGeometry(QtCore.QRect(450, 150, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.label_85.setFont(font)
        self.label_85.setStyleSheet("border-color: #77afe3;\n"
"border-width :1px;\n"
"border-style:solid;\n"
"border-radius:8px;\n"
"    background-color: rgb(255, 255, 255);\n"
"")
        self.label_85.setShadowEnabled(True)
        self.label_85.setShadowRadius(5)
        self.label_85.setShadowOffset(QtCore.QPointF(2.0, 2.0))
        self.label_85.setShadowColor(QtGui.QColor(119, 175, 227))
        self.label_85.setObjectName("label_85")
        self.label_12 = LTLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(30, 180, 121, 30))
        self.label_12.setObjectName("label_12")
        self.label_22.raise_()
        self.label_2.raise_()
        self.label_23.raise_()
        self.label_19.raise_()
        self.tablewidget_Maintenance_10.raise_()
        self.Refresh_network_stat.raise_()
        self.label_84.raise_()
        self.label_86.raise_()
        self.tagproperties1_38.raise_()
        self.label_85.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.tagproperties1_39.raise_()
        self.tagproperties1_40.raise_()
        self.label_14.raise_()
        self.tabwidget.addTab(self.tab, "Network Info")
        self.Tab_5 = LTWidget()
        self.Tab_5.setObjectName("Tab_5")
        self.tablewidget_Maintenance_6 = LTTableWidget(self.Tab_5)
        self.tablewidget_Maintenance_6.setGeometry(QtCore.QRect(640, 160, 610, 500))
        self.tablewidget_Maintenance_6.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"alternate-background-color: rgb(222, 222, 222);")
        self.tablewidget_Maintenance_6.setObjectName("tablewidget_Maintenance_6")
        self.tablewidget_Maintenance_6.setColumnCount(4)
        self.tablewidget_Maintenance_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_Maintenance_6.setHorizontalHeaderItem(3, item)
        self.tablewidget_Maintenance_8 = LTTableWidget(self.Tab_5)
        self.tablewidget_Maintenance_8.setGeometry(QtCore.QRect(10, 160, 610, 500))
        self.tablewidget_Maintenance_8.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"alternate-background-color: rgb(222, 222, 222);")
        self.tablewidget_Maintenance_8.setObjectName("tablewidget_Maintenance_8")
        self.tablewidget_Maintenance_8.setColumnCount(5)
        self.tablewidget_Maintenance_8.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_Maintenance_8.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_Maintenance_8.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_Maintenance_8.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_Maintenance_8.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_Maintenance_8.setHorizontalHeaderItem(4, item)
        self.label_27 = LTLabel(self.Tab_5)
        self.label_27.setGeometry(QtCore.QRect(5, 80, 620, 590))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("border-color: #f25c5c;\n"
"border-width :1px;\n"
"border-style:solid;\n"
"border-radius:8px;\n"
"    background-color: rgb(255, 255, 255);\n"
"")
        self.label_27.setShadowEnabled(True)
        self.label_27.setShadowRadius(5)
        self.label_27.setShadowOffset(QtCore.QPointF(2.0, 2.0))
        self.label_27.setShadowColor(QtGui.QColor(242, 92, 92, 180))
        self.label_27.setObjectName("label_27")
        self.label_24 = LTLabel(self.Tab_5)
        self.label_24.setGeometry(QtCore.QRect(510, 10, 241, 30))
        self.label_24.setObjectName("label_24")
        self.label_28 = LTLabel(self.Tab_5)
        self.label_28.setGeometry(QtCore.QRect(635, 80, 620, 590))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("border-color: #f25c5c;\n"
"border-width :1px;\n"
"border-style:solid;\n"
"border-radius:8px;\n"
"    background-color: rgb(255, 255, 255);\n"
"")
        self.label_28.setShadowEnabled(True)
        self.label_28.setShadowRadius(5)
        self.label_28.setShadowOffset(QtCore.QPointF(2.0, 2.0))
        self.label_28.setShadowColor(QtGui.QColor(242, 92, 92, 180))
        self.label_28.setObjectName("label_28")
        self.label_25 = LTLabel(self.Tab_5)
        self.label_25.setGeometry(QtCore.QRect(180, 110, 241, 30))
        self.label_25.setObjectName("label_25")
        self.label_26 = LTLabel(self.Tab_5)
        self.label_26.setGeometry(QtCore.QRect(830, 110, 241, 30))
        self.label_26.setObjectName("label_26")
        self.Refresh_server_infra = LTPushButton(self.Tab_5)
        self.Refresh_server_infra.setGeometry(QtCore.QRect(540, 40, 181, 30))
        self.Refresh_server_infra.setObjectName("Refresh_server_infra")
        self.label_28.raise_()
        self.label_27.raise_()
        self.tablewidget_Maintenance_6.raise_()
        self.tablewidget_Maintenance_8.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.Refresh_server_infra.raise_()
        self.tabwidget.addTab(self.Tab_5, "Server Infra")

        self.retranslateUi(widgetUI)
        self.tabwidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(widgetUI)

    def retranslateUi(self, widgetUI):
        _translate = QtCore.QCoreApplication.translate
        widgetUI.setWindowTitle(_translate("widgetUI", "Screen"))
        widgetUI.setInternalUse(_translate("widgetUI", "1,1"))
        self.tab_1.setInternalUse(_translate("widgetUI", "1,1"))
        item = self.tablewidget_Trip_2.horizontalHeaderItem(0)
        item.setText(_translate("widgetUI", "Modules Information"))
        item = self.tablewidget_Trip_2.horizontalHeaderItem(1)
        item.setText(_translate("widgetUI", "Status"))
        self.label.setText(_translate("widgetUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Module Active</span></p></body></html>"))
        self.cpu_label_1.setText(_translate("widgetUI", "<html><head/><body><p align=\"center\"><span style=\" color:#005c8e;\">CPU Utilization</span></p></body></html>"))
        self.cpu_label_3.setText(_translate("widgetUI", "<html><head/><body><p align=\"center\"><span style=\" color:#005c8e;\">Storage</span></p></body></html>"))
        self.cpu_label_2.setText(_translate("widgetUI", "<html><head/><body><p align=\"center\"><span style=\" color:#005c8e;\">RAM Utilization</span></p></body></html>"))
        self.Refresh_mod_active.setText(_translate("widgetUI", "Refresh"))
        self.tab_2.setInternalUse(_translate("widgetUI", "1,1"))
        item = self.tablewidget_Maintenance_4.horizontalHeaderItem(0)
        item.setText(_translate("widgetUI", "Time"))
        item = self.tablewidget_Maintenance_4.horizontalHeaderItem(1)
        item.setText(_translate("widgetUI", "PID"))
        item = self.tablewidget_Maintenance_4.horizontalHeaderItem(2)
        item.setText(_translate("widgetUI", "Application Name"))
        item = self.tablewidget_Maintenance_4.horizontalHeaderItem(3)
        item.setText(_translate("widgetUI", "Status"))
        item = self.tablewidget_Maintenance_4.horizontalHeaderItem(4)
        item.setText(_translate("widgetUI", "Memory Utilization in (MB)"))
        item = self.tablewidget_Maintenance_4.horizontalHeaderItem(5)
        item.setText(_translate("widgetUI", "Cpu Utilization % "))
        self.label_9.setText(_translate("widgetUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Application Information</span></p></body></html>"))
        self.Refresh_appinfo.setText(_translate("widgetUI", "Refresh"))
        self.tab_3.setInternalUse(_translate("widgetUI", "1,1"))
        item = self.tablewidget_Maintenance_2.horizontalHeaderItem(0)
        item.setText(_translate("widgetUI", "TimeStamp"))
        item = self.tablewidget_Maintenance_2.horizontalHeaderItem(1)
        item.setText(_translate("widgetUI", "Start Live Count"))
        self.label_8.setText(_translate("widgetUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Start Live Count</span></p></body></html>"))
        self.Refresh_startlive.setText(_translate("widgetUI", "Refresh"))
        self.tab.setInternalUse(_translate("widgetUI", "1,1"))
        item = self.tablewidget_Maintenance_10.horizontalHeaderItem(0)
        item.setText(_translate("widgetUI", "Active Interfaces"))
        item = self.tablewidget_Maintenance_10.horizontalHeaderItem(1)
        item.setText(_translate("widgetUI", "Connection Status"))
        self.label_19.setText(_translate("widgetUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Network Statistics</span></p></body></html>"))
        self.Refresh_network_stat.setText(_translate("widgetUI", "Refresh"))
        self.label_14.setText(_translate("widgetUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Total Speed</span></p></body></html>"))
        self.label_13.setText(_translate("widgetUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Download Speed</span></p></body></html>"))
        self.label_12.setText(_translate("widgetUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Upload Speed</span></p></body></html>"))
        self.Tab_5.setInternalUse(_translate("widgetUI", "1,1"))
        item = self.tablewidget_Maintenance_6.horizontalHeaderItem(0)
        item.setText(_translate("widgetUI", "Cpu per core"))
        item = self.tablewidget_Maintenance_6.horizontalHeaderItem(1)
        item.setText(_translate("widgetUI", "Cpu logical cores"))
        item = self.tablewidget_Maintenance_6.horizontalHeaderItem(2)
        item.setText(_translate("widgetUI", "Cpu physical cores"))
        item = self.tablewidget_Maintenance_6.horizontalHeaderItem(3)
        item.setText(_translate("widgetUI", "Cpu cores being used"))
        item = self.tablewidget_Maintenance_8.horizontalHeaderItem(0)
        item.setText(_translate("widgetUI", "Drive Name"))
        item = self.tablewidget_Maintenance_8.horizontalHeaderItem(1)
        item.setText(_translate("widgetUI", "Total Space (GB)"))
        item = self.tablewidget_Maintenance_8.horizontalHeaderItem(2)
        item.setText(_translate("widgetUI", "Used Space (GB)"))
        item = self.tablewidget_Maintenance_8.horizontalHeaderItem(3)
        item.setText(_translate("widgetUI", "New Column"))
        item = self.tablewidget_Maintenance_8.horizontalHeaderItem(4)
        item.setText(_translate("widgetUI", "Usage (%)"))
        self.label_24.setText(_translate("widgetUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Server Infrastructure</span></p></body></html>"))
        self.label_25.setText(_translate("widgetUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Drive Information</span></p></body></html>"))
        self.label_26.setText(_translate("widgetUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Cores Information</span></p></body></html>"))
        self.Refresh_server_infra.setText(_translate("widgetUI", "Refresh"))


from TrendStatic import TrendStatic
from ctwgPieChartDonut import ctwgPieChartDonut
from ltlabel import LTLabel
from ltpushbutton import LTPushButton
from lttablewidget import LTTableWidget
from lttabwidget import LTTabWidget
from ltwidget import LTWidget
from tagProperties1 import tagProperties1
