# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/SmartComm/iVisionmax/screens/user/Diagnostic Module/UI/widgetUI.screen'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widgetUI(object):
    def setupUi(self, widgetUI):
        widgetUI.setObjectName("widgetUI")
        widgetUI.resize(1296, 872)
        self.tabwidget = LTTabWidget(widgetUI)
        self.tabwidget.setGeometry(QtCore.QRect(3, 4, 1290, 880))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.tabwidget.setFont(font)
        self.tabwidget.setAutoFillBackground(False)
        self.tabwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabwidget.setObjectName("tabwidget")
        self.tab_1 = LTWidget()
        self.tab_1.setBackgroundColor(QtGui.QColor(240, 240, 240))
        self.tab_1.setObjectName("tab_1")
        self.tablewidget_Trip_2 = LTTableWidget(self.tab_1)
        self.tablewidget_Trip_2.setGeometry(QtCore.QRect(680, 70, 561, 280))
        self.tablewidget_Trip_2.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"alternate-background-color: rgb(222, 222, 222);")
        self.tablewidget_Trip_2.setObjectName("tablewidget_Trip_2")
        self.tablewidget_Trip_2.setColumnCount(2)
        self.tablewidget_Trip_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_Trip_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_Trip_2.setHorizontalHeaderItem(1, item)
        self.layoutWidget = QtWidgets.QWidget(self.tab_1)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 60, 610, 240))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cpu = ctwgPieChartDonut(self.layoutWidget)
        self.cpu.setProperty("tagName", "Obj1.Server_Infra.cpu")
        self.cpu.setProperty("value", 0.0)
        self.cpu.setObjectName("cpu")
        self.horizontalLayout_2.addWidget(self.cpu)
        self.ram = ctwgPieChartDonut(self.layoutWidget)
        self.ram.setProperty("tagName", "Obj1.Server_Infra.ram")
        self.ram.setProperty("value", 0.0)
        self.ram.setObjectName("ram")
        self.horizontalLayout_2.addWidget(self.ram)
        self.storage = ctwgPieChartDonut(self.layoutWidget)
        self.storage.setProperty("tagName", "Obj1.Server_Infra.storage")
        self.storage.setProperty("value", 0.0)
        self.storage.setObjectName("storage")
        self.horizontalLayout_2.addWidget(self.storage)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cpu_label = LTLabel(self.layoutWidget)
        self.cpu_label.setBackgroundColor(QtGui.QColor(0, 0, 255))
        self.cpu_label.setObjectName("cpu_label")
        self.horizontalLayout_3.addWidget(self.cpu_label)
        self.ram_label = LTLabel(self.layoutWidget)
        self.ram_label.setBackgroundColor(QtGui.QColor(0, 0, 255))
        self.ram_label.setObjectName("ram_label")
        self.horizontalLayout_3.addWidget(self.ram_label)
        self.strorage_label = LTLabel(self.layoutWidget)
        self.strorage_label.setBackgroundColor(QtGui.QColor(0, 0, 255))
        self.strorage_label.setObjectName("strorage_label")
        self.horizontalLayout_3.addWidget(self.strorage_label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label = LTLabel(self.tab_1)
        self.label.setGeometry(QtCore.QRect(900, 30, 140, 30))
        self.label.setObjectName("label")
        self.trendstatic = TrendStatic(self.tab_1)
        self.trendstatic.setGeometry(QtCore.QRect(70, 390, 500, 381))
        self.trendstatic.setObjectName("trendstatic")
        self.tabwidget.addTab(self.tab_1, "Dashboard")
        self.tab_2 = LTWidget()
        self.tab_2.setBackgroundColor(QtGui.QColor(240, 240, 240))
        self.tab_2.setObjectName("tab_2")
        self.tablewidget_Event_2 = LTTableWidget(self.tab_2)
        self.tablewidget_Event_2.setGeometry(QtCore.QRect(10, 8, 631, 530))
        self.tablewidget_Event_2.setMaximumSize(QtCore.QSize(631, 16777215))
        self.tablewidget_Event_2.setAutoFillBackground(True)
        self.tablewidget_Event_2.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"alternate-background-color: rgb(222, 222, 222);")
        self.tablewidget_Event_2.setObjectName("tablewidget_Event_2")
        self.tablewidget_Event_2.setColumnCount(5)
        self.tablewidget_Event_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Event_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignBottom)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Event_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Event_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_Event_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_Event_2.setHorizontalHeaderItem(4, item)
        self.tabwidget.addTab(self.tab_2, "Application Info")
        self.tab_3 = LTWidget()
        self.tab_3.setBackgroundColor(QtGui.QColor(240, 240, 240))
        self.tab_3.setObjectName("tab_3")
        self.cmbMaintenance_2 = LTComboBox(self.tab_3)
        self.cmbMaintenance_2.setGeometry(QtCore.QRect(155, 10, 210, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.cmbMaintenance_2.setFont(font)
        self.cmbMaintenance_2.setBackgroundColor(QtGui.QColor(240, 240, 240))
        self.cmbMaintenance_2.setObjectName("cmbMaintenance_2")
        self.tablewidget_Maintenance_2 = LTTableWidget(self.tab_3)
        self.tablewidget_Maintenance_2.setGeometry(QtCore.QRect(7, 47, 640, 481))
        self.tablewidget_Maintenance_2.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"alternate-background-color: rgb(222, 222, 222);")
        self.tablewidget_Maintenance_2.setObjectName("tablewidget_Maintenance_2")
        self.tablewidget_Maintenance_2.setColumnCount(3)
        self.tablewidget_Maintenance_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_2.setHorizontalHeaderItem(2, item)
        self.label_40 = LTLabel(self.tab_3)
        self.label_40.setGeometry(QtCore.QRect(10, 10, 140, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("QLabel{\n"
"border-color: rgb(112,112,112);\n"
"border-width :0px;\n"
"border-style:solid;\n"
"}\n"
"QLabel{\n"
"background-color:rgb(206,206,206);\n"
"}\n"
"")
        self.label_40.setObjectName("label_40")
        self.pushbutton_6 = LTPushButton(self.tab_3)
        self.pushbutton_6.setGeometry(QtCore.QRect(376, 9, 61, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushbutton_6.setFont(font)
        self.pushbutton_6.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushbutton_6.setObjectName("pushbutton_6")
        self.tabwidget.addTab(self.tab_3, "Addition Module Information")
        self.tab_4 = LTWidget()
        self.tab_4.setObjectName("tab_4")
        self.tablewidget_Maintenance_4 = LTTableWidget(self.tab_4)
        self.tablewidget_Maintenance_4.setGeometry(QtCore.QRect(10, 10, 640, 520))
        self.tablewidget_Maintenance_4.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"alternate-background-color: rgb(222, 222, 222);")
        self.tablewidget_Maintenance_4.setObjectName("tablewidget_Maintenance_4")
        self.tablewidget_Maintenance_4.setColumnCount(3)
        self.tablewidget_Maintenance_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_4.setHorizontalHeaderItem(2, item)
        self.tabwidget.addTab(self.tab_4, "Network Information")
        self.Tab_5 = LTWidget()
        self.Tab_5.setObjectName("Tab_5")
        self.tabwidget.addTab(self.Tab_5, "Server Infra")

        self.retranslateUi(widgetUI)
        self.tabwidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(widgetUI)

    def retranslateUi(self, widgetUI):
        _translate = QtCore.QCoreApplication.translate
        widgetUI.setWindowTitle(_translate("widgetUI", "Screen"))
        widgetUI.setInternalUse(_translate("widgetUI", "1,1"))
        self.tab_1.setInternalUse(_translate("widgetUI", "1,1"))
        item = self.tablewidget_Trip_2.horizontalHeaderItem(0)
        item.setText(_translate("widgetUI", "Modules Information"))
        item = self.tablewidget_Trip_2.horizontalHeaderItem(1)
        item.setText(_translate("widgetUI", "Status"))
        self.cpu_label.setText(_translate("widgetUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; color:#ffffff;\">CPU Utilization</span></p></body></html>"))
        self.ram_label.setText(_translate("widgetUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; color:#ffffff;\">RAM Utilization</span></p></body></html>"))
        self.strorage_label.setText(_translate("widgetUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; color:#ffffff;\">STORAGE</span></p></body></html>"))
        self.label.setText(_translate("widgetUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Module Active</span></p></body></html>"))
        self.tab_2.setInternalUse(_translate("widgetUI", "1,1"))
        item = self.tablewidget_Event_2.horizontalHeaderItem(0)
        item.setText(_translate("widgetUI", "Time"))
        item = self.tablewidget_Event_2.horizontalHeaderItem(1)
        item.setText(_translate("widgetUI", "Application Name"))
        item = self.tablewidget_Event_2.horizontalHeaderItem(2)
        item.setText(_translate("widgetUI", "Unit"))
        item = self.tablewidget_Event_2.horizontalHeaderItem(3)
        item.setText(_translate("widgetUI", "Ram Utilization"))
        item = self.tablewidget_Event_2.horizontalHeaderItem(4)
        item.setText(_translate("widgetUI", "Cpu Utilization"))
        self.tab_3.setInternalUse(_translate("widgetUI", "1,1"))
        item = self.tablewidget_Maintenance_2.horizontalHeaderItem(0)
        item.setText(_translate("widgetUI", "Time"))
        item = self.tablewidget_Maintenance_2.horizontalHeaderItem(1)
        item.setText(_translate("widgetUI", "Parameter"))
        item = self.tablewidget_Maintenance_2.horizontalHeaderItem(2)
        item.setText(_translate("widgetUI", "Condition"))
        self.label_40.setText(_translate("widgetUI", "Modules"))
        self.pushbutton_6.setText(_translate("widgetUI", "Show"))
        self.tab_4.setInternalUse(_translate("widgetUI", "1,1"))
        item = self.tablewidget_Maintenance_4.horizontalHeaderItem(0)
        item.setText(_translate("widgetUI", "Time"))
        item = self.tablewidget_Maintenance_4.horizontalHeaderItem(1)
        item.setText(_translate("widgetUI", "Interface "))
        item = self.tablewidget_Maintenance_4.horizontalHeaderItem(2)
        item.setText(_translate("widgetUI", "IP Address"))
        self.Tab_5.setInternalUse(_translate("widgetUI", "1,1"))


from TrendStatic import TrendStatic
from ctwgPieChartDonut import ctwgPieChartDonut
from ltcombobox import LTComboBox
from ltlabel import LTLabel
from ltpushbutton import LTPushButton
from lttablewidget import LTTableWidget
from lttabwidget import LTTabWidget
from ltwidget import LTWidget
