# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/SmartComm/iVisionmax/screens/user/Diagnostic Module/UI/widgetUI.screen'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widgetUI(object):
    def setupUi(self, widgetUI):
        widgetUI.setObjectName("widgetUI")
        widgetUI.resize(1276, 816)
        self.tabwidget = LTTabWidget(widgetUI)
        self.tabwidget.setGeometry(QtCore.QRect(4, 4, 1270, 810))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.tabwidget.setFont(font)
        self.tabwidget.setAutoFillBackground(False)
        self.tabwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabwidget.setObjectName("tabwidget")
        self.tab_1 = LTWidget()
        self.tab_1.setBackgroundColor(QtGui.QColor(240, 240, 240))
        self.tab_1.setObjectName("tab_1")
        self.tablewidget_Trip_2 = LTTableWidget(self.tab_1)
        self.tablewidget_Trip_2.setGeometry(QtCore.QRect(670, 70, 561, 300))
        self.tablewidget_Trip_2.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"alternate-background-color: rgb(222, 222, 222);")
        self.tablewidget_Trip_2.setObjectName("tablewidget_Trip_2")
        self.tablewidget_Trip_2.setColumnCount(2)
        self.tablewidget_Trip_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_Trip_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_Trip_2.setHorizontalHeaderItem(1, item)
        self.layoutWidget = QtWidgets.QWidget(self.tab_1)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 70, 600, 300))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cpu = ctwgPieChartDonut(self.layoutWidget)
        self.cpu.setProperty("tagName", "Obj1.Server_Infra.cpu")
        self.cpu.setProperty("value", 0.0)
        self.cpu.setObjectName("cpu")
        self.horizontalLayout_2.addWidget(self.cpu)
        self.ram = ctwgPieChartDonut(self.layoutWidget)
        self.ram.setProperty("tagName", "Obj1.Server_Infra.ram")
        self.ram.setProperty("value", 0.0)
        self.ram.setObjectName("ram")
        self.horizontalLayout_2.addWidget(self.ram)
        self.storage = ctwgPieChartDonut(self.layoutWidget)
        self.storage.setProperty("tagName", "Obj1.Server_Infra.storage")
        self.storage.setProperty("value", 0.0)
        self.storage.setObjectName("storage")
        self.horizontalLayout_2.addWidget(self.storage)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cpu_label = LTLabel(self.layoutWidget)
        self.cpu_label.setBackgroundColor(QtGui.QColor(0, 0, 255))
        self.cpu_label.setObjectName("cpu_label")
        self.horizontalLayout_3.addWidget(self.cpu_label)
        self.ram_label = LTLabel(self.layoutWidget)
        self.ram_label.setBackgroundColor(QtGui.QColor(0, 0, 255))
        self.ram_label.setObjectName("ram_label")
        self.horizontalLayout_3.addWidget(self.ram_label)
        self.strorage_label = LTLabel(self.layoutWidget)
        self.strorage_label.setBackgroundColor(QtGui.QColor(0, 0, 255))
        self.strorage_label.setObjectName("strorage_label")
        self.horizontalLayout_3.addWidget(self.strorage_label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label = LTLabel(self.tab_1)
        self.label.setGeometry(QtCore.QRect(890, 30, 130, 30))
        self.label.setObjectName("label")
        self.trendstatic = TrendStatic(self.tab_1)
        self.trendstatic.setGeometry(QtCore.QRect(20, 380, 1230, 390))
        self.trendstatic.setObjectName("trendstatic")
        self.tabwidget.addTab(self.tab_1, "Dashboard")
        self.tab_2 = LTWidget()
        self.tab_2.setBackgroundColor(QtGui.QColor(240, 240, 240))
        self.tab_2.setObjectName("tab_2")
        self.tablewidget_Maintenance_3 = LTTableWidget(self.tab_2)
        self.tablewidget_Maintenance_3.setGeometry(QtCore.QRect(6, 8, 1250, 770))
        self.tablewidget_Maintenance_3.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"alternate-background-color: rgb(222, 222, 222);")
        self.tablewidget_Maintenance_3.setObjectName("tablewidget_Maintenance_3")
        self.tablewidget_Maintenance_3.setColumnCount(3)
        self.tablewidget_Maintenance_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_3.setHorizontalHeaderItem(2, item)
        self.tabwidget.addTab(self.tab_2, "Application Info")
        self.tab_3 = LTWidget()
        self.tab_3.setBackgroundColor(QtGui.QColor(240, 240, 240))
        self.tab_3.setObjectName("tab_3")
        self.tablewidget_Maintenance_2 = LTTableWidget(self.tab_3)
        self.tablewidget_Maintenance_2.setGeometry(QtCore.QRect(8, 8, 1250, 760))
        self.tablewidget_Maintenance_2.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"alternate-background-color: rgb(222, 222, 222);")
        self.tablewidget_Maintenance_2.setObjectName("tablewidget_Maintenance_2")
        self.tablewidget_Maintenance_2.setColumnCount(3)
        self.tablewidget_Maintenance_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_2.setHorizontalHeaderItem(2, item)
        self.tabwidget.addTab(self.tab_3, "Addition Module Information")
        self.tab_4 = LTWidget()
        self.tab_4.setObjectName("tab_4")
        self.tablewidget_Maintenance_4 = LTTableWidget(self.tab_4)
        self.tablewidget_Maintenance_4.setGeometry(QtCore.QRect(10, 10, 660, 340))
        self.tablewidget_Maintenance_4.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"alternate-background-color: rgb(222, 222, 222);")
        self.tablewidget_Maintenance_4.setObjectName("tablewidget_Maintenance_4")
        self.tablewidget_Maintenance_4.setColumnCount(3)
        self.tablewidget_Maintenance_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_4.setHorizontalHeaderItem(2, item)
        self.tablewidget_Maintenance_7 = LTTableWidget(self.tab_4)
        self.tablewidget_Maintenance_7.setGeometry(QtCore.QRect(580, 400, 660, 340))
        self.tablewidget_Maintenance_7.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"alternate-background-color: rgb(222, 222, 222);")
        self.tablewidget_Maintenance_7.setObjectName("tablewidget_Maintenance_7")
        self.tablewidget_Maintenance_7.setColumnCount(3)
        self.tablewidget_Maintenance_7.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_7.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_7.setHorizontalHeaderItem(2, item)
        self.tabwidget.addTab(self.tab_4, "Network Information")
        self.Tab_5 = LTWidget()
        self.Tab_5.setObjectName("Tab_5")
        self.tablewidget_Maintenance_5 = LTTableWidget(self.Tab_5)
        self.tablewidget_Maintenance_5.setGeometry(QtCore.QRect(10, 10, 610, 360))
        self.tablewidget_Maintenance_5.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"alternate-background-color: rgb(222, 222, 222);")
        self.tablewidget_Maintenance_5.setObjectName("tablewidget_Maintenance_5")
        self.tablewidget_Maintenance_5.setColumnCount(3)
        self.tablewidget_Maintenance_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_5.setHorizontalHeaderItem(2, item)
        self.tablewidget_Maintenance_6 = LTTableWidget(self.Tab_5)
        self.tablewidget_Maintenance_6.setGeometry(QtCore.QRect(640, 10, 610, 360))
        self.tablewidget_Maintenance_6.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"alternate-background-color: rgb(222, 222, 222);")
        self.tablewidget_Maintenance_6.setObjectName("tablewidget_Maintenance_6")
        self.tablewidget_Maintenance_6.setColumnCount(3)
        self.tablewidget_Maintenance_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tablewidget_Maintenance_6.setHorizontalHeaderItem(2, item)
        self.tabwidget.addTab(self.Tab_5, "Server Infra")

        self.retranslateUi(widgetUI)
        self.tabwidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(widgetUI)

    def retranslateUi(self, widgetUI):
        _translate = QtCore.QCoreApplication.translate
        widgetUI.setWindowTitle(_translate("widgetUI", "Screen"))
        widgetUI.setInternalUse(_translate("widgetUI", "1,1"))
        self.tab_1.setInternalUse(_translate("widgetUI", "1,1"))
        item = self.tablewidget_Trip_2.horizontalHeaderItem(0)
        item.setText(_translate("widgetUI", "Modules Information"))
        item = self.tablewidget_Trip_2.horizontalHeaderItem(1)
        item.setText(_translate("widgetUI", "Status"))
        self.cpu_label.setText(_translate("widgetUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; color:#ffffff;\">CPU Utilization</span></p></body></html>"))
        self.ram_label.setText(_translate("widgetUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; color:#ffffff;\">RAM Utilization</span></p></body></html>"))
        self.strorage_label.setText(_translate("widgetUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; color:#ffffff;\">STORAGE</span></p></body></html>"))
        self.label.setText(_translate("widgetUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Module Active</span></p></body></html>"))
        self.tab_2.setInternalUse(_translate("widgetUI", "1,1"))
        item = self.tablewidget_Maintenance_3.horizontalHeaderItem(0)
        item.setText(_translate("widgetUI", "Time"))
        item = self.tablewidget_Maintenance_3.horizontalHeaderItem(1)
        item.setText(_translate("widgetUI", "Parameter"))
        item = self.tablewidget_Maintenance_3.horizontalHeaderItem(2)
        item.setText(_translate("widgetUI", "Condition"))
        self.tab_3.setInternalUse(_translate("widgetUI", "1,1"))
        item = self.tablewidget_Maintenance_2.horizontalHeaderItem(0)
        item.setText(_translate("widgetUI", "Time"))
        item = self.tablewidget_Maintenance_2.horizontalHeaderItem(1)
        item.setText(_translate("widgetUI", "Parameter"))
        item = self.tablewidget_Maintenance_2.horizontalHeaderItem(2)
        item.setText(_translate("widgetUI", "Condition"))
        self.tab_4.setInternalUse(_translate("widgetUI", "1,1"))
        item = self.tablewidget_Maintenance_4.horizontalHeaderItem(0)
        item.setText(_translate("widgetUI", "Time"))
        item = self.tablewidget_Maintenance_4.horizontalHeaderItem(1)
        item.setText(_translate("widgetUI", "Interface "))
        item = self.tablewidget_Maintenance_4.horizontalHeaderItem(2)
        item.setText(_translate("widgetUI", "IP Address"))
        item = self.tablewidget_Maintenance_7.horizontalHeaderItem(0)
        item.setText(_translate("widgetUI", "Time"))
        item = self.tablewidget_Maintenance_7.horizontalHeaderItem(1)
        item.setText(_translate("widgetUI", "Interface "))
        item = self.tablewidget_Maintenance_7.horizontalHeaderItem(2)
        item.setText(_translate("widgetUI", "IP Address"))
        self.Tab_5.setInternalUse(_translate("widgetUI", "1,1"))
        item = self.tablewidget_Maintenance_5.horizontalHeaderItem(0)
        item.setText(_translate("widgetUI", "Time"))
        item = self.tablewidget_Maintenance_5.horizontalHeaderItem(1)
        item.setText(_translate("widgetUI", "Parameter"))
        item = self.tablewidget_Maintenance_5.horizontalHeaderItem(2)
        item.setText(_translate("widgetUI", "Condition"))
        item = self.tablewidget_Maintenance_6.horizontalHeaderItem(0)
        item.setText(_translate("widgetUI", "Time"))
        item = self.tablewidget_Maintenance_6.horizontalHeaderItem(1)
        item.setText(_translate("widgetUI", "Parameter"))
        item = self.tablewidget_Maintenance_6.horizontalHeaderItem(2)
        item.setText(_translate("widgetUI", "Condition"))


from TrendStatic import TrendStatic
from ctwgPieChartDonut import ctwgPieChartDonut
from ltlabel import LTLabel
from lttablewidget import LTTableWidget
from lttabwidget import LTTabWidget
from ltwidget import LTWidget
